[34m[1mwandb[0m: [33mWARNING[0m Calling wandb.run.save without any arguments is deprecated.Changes to attributes are automatically persisted.
Epoch 1/30 - Train Loss: 0.5041, Train Acc: 0.8181, Val Loss: 0.3876, Val Acc: 0.8598
Traceback (most recent call last):
  File "C:\Users\skrit\Documents\IntroDL\DA6401_Assgn1\train.py", line 199, in <module>
    main()
  File "C:\Users\skrit\Documents\IntroDL\DA6401_Assgn1\train.py", line 160, in main
    np.save(filename, nn.parameters)
  File "C:\Users\skrit\miniconda3\envs\medllm\Lib\site-packages\numpy\lib\npyio.py", line 542, in save
    file_ctx = open(file, "wb")
               ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'fmodels/hl_3_hs_256_bs_256_ep_30_ac_tanh_o_nadam_lr_0.001_wd_0.0_wi_Xavier_dataset_fashion_mnist_loss_cross_entropy.npy'
